name: "Terraform Production Deployment"

# Trigger ONLY on a direct push or merged Pull Request to the main branch
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: "OIDC Auth & Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Authenticate to AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::929746712415:role/terraform-auth
          aws-region: us-east-1
          audience: ://amazonaws.com

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # Prevents stdout wrapping issues if needed
    # Notice we don't pass a hardcoded version string anymore!


      # 4. Initialize Terraform Backend
      - name: Terraform Init
        run: terraform init

      # 5. Check formatting syntax
      - name: Terraform Format Check
        run: terraform fmt -check

      # 6. Optional but recommended: Run a plan first so it shows up in your workflow logs
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -no-color

      # 7. Apply the changes automatically using the variables file
      - name: Terraform Apply
        run: terraform apply -auto-approve
